### ISSUE TITLE
Replication packets are served before they are fully copied

### ISSUE THREAD

**Issue by gentlecat** [metabrainz/metabrainz.org#100]
See http://chatlogs.musicbrainz.org/musicbrainz-devel/2015/2015-05/2015-05-06.html#T06-26-48-901561.

**Comment by gentlecat** [comment]
Closing because http://chatlogs.musicbrainz.org/musicbrainz-devel/2015/2015-05/2015-05-06.html#T09-09-04-513322.

**Comment by mayhem** [comment]
Fixed.
