### ISSUE TITLE
Add database field to track actual amount pledged

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#105]
Right now we track the tiers, but those only define thresholds. In the signup page we should include a field (amount_pledged) that allows the user to pick an actual amount to support us with. 

The text for this should read:

"If you would like to support us with more than $tier_threshold_amount, please enter the actual amount here:"

This field should initially be populated with $tier_threshold_amount, and this field should not be user editable.

**Comment by gentlecat** [comment]
How will they enter `amount_pledged` if field is not editable?

**Comment by mayhem** [comment]
That was in reference to the now closed bug that allowed users to edit their data. Now moot.
