### ISSUE TITLE
Signup with new user account

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#124]
When a user signs up and creates a new MusicBrainz account, they are never returned to MetaBrainz. Can we fix this without requiring a change at MusicBrainz?

**Comment by ianmcorvidae** [comment]
changed at MusicBrainz, as mentioned in IRC: https://bitbucket.org/metabrainz/musicbrainz-server/pull-request/1582/factor-out-the-account-register-url/diff :P

**Comment by gentlecat** [comment]
Closing since we don't need to do anything there.
