### ISSUE TITLE
Support Us is not clear how to sign up for non-profit

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#125]
We could just show the non-profit tier, but that would make the page ugly. Maybe add a link in the non-commercial section that links the non-proft tier?

**Comment by gentlecat** [comment]
I feel like linking directly to items defined in the database from application/templates is a bad idea.

If *non-profit* tier is still considered "commercial", then the best approach might be to tweak layout to make it work with a number of tiers that need to be displayed on the page. Design shouldn't get in the way in the first place.

**Comment by mayhem** [comment]
I agree with you, but I don't know how to get from here to there. :(
