### ISSUE TITLE
Add note about arranging payment details

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#126]
"we'll send you more details once your application is approved" is one suggestion for how to fix this.

**Comment by mayhem** [comment]
Note for non-profit users: Choose paypal -- you won't be required to pay.
Note for open source users: Don't sweat the address.

**Comment by gentlecat** [comment]
Problem is that non-profit and open source users are defined in the database, not application.

**Comment by gentlecat** [comment]
@mayhem, should we close this?
