### ISSUE TITLE
Possible solution to the Support Us layout problem

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#138]
Nico suggested that we can fix the page like this:

![screenshot-test metabrainz org 2015-05-14 19-54-14](https://cloud.githubusercontent.com/assets/49745/7641259/cfbfe314-fa88-11e4-94a3-1b44078c440d.png)

(maybe add something about "these are our favorite unicorns -- see them all here")

Visually that works ok, but I am not certain how to implement this in a way that won't suck. Thoughts?

**Comment by gentlecat** [comment]
#125
