### ISSUE TITLE
Update content

### ISSUE THREAD

**Issue by gentlecat** [metabrainz/metabrainz.org#42]
All text needs to be reviewed and updated if needed. I left *TODO* comments that can be used as a reference in some templates.

**Comment by Freso** [comment]
Maybe mention dotsrc.org on /sponsors for hosting the EU FTP mirror?

**Comment by mayhem** [comment]
Freso: I would love a PR for dosrc.org!!

**Comment by gentlecat** [comment]
Need to copy new financial reports as well. See https://github.com/metabrainz/metabrainz.org/tree/master/metabrainz/reports/financial_reports.

**Comment by gentlecat** [comment]
Page about users with a bad standing needs some text.
https://test.metabrainz.org/supporters/bad
https://github.com/metabrainz/metabrainz.org/blob/master/metabrainz/templates/users/bad-standing.html

**Comment by mayhem** [comment]
Financial reports have been added.

**Comment by mayhem** [comment]
> https://test.metabrainz.org/supporters/bad

That got some text a while ago. Done.

**Comment by mayhem** [comment]
There are no more TODOs in the templates.

**Comment by mayhem** [comment]
Commit 60c5082aec7834 adds dotsrc to the sponsors. Once PR #149 closes, this issue can be closed.
