### ISSUE TITLE
Increase size of large text edit fields

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#65]
Fields like the Long Description in the Tier page should allow the user more space to enter text.

**Comment by tsukanov** [comment]
On admin pages?

**Comment by mayhem** [comment]
Primarily, yes. But if there is a field that is customer facing, it should be large on their side too.

**Comment by tsukanov** [comment]
It is multirow textfield on customer facing side. I'll see what can be done about admin interface.

**Comment by tsukanov** [comment]
Fixed in 4c354ce7abbee3165c8cf82234a467d1e44de51c. :shipit:
