### ISSUE TITLE
Access tokens page should list name of user, not just id

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#71]
This is nice to have, but not required.

**Comment by tsukanov** [comment]
Yeah, that's on my list. Same for references to tiers.

**Comment by tsukanov** [comment]
Done. See 04e1055349b5e1a8f25fea8400bd7656b2d9d499 and 9db1d845da7bf69cc5a56f98a68f5521bbcb0290. :shipit:
