### ISSUE TITLE
Sign Up -> Support us!

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#90]
We should use say "Support us" instead of "Sign up". Please change the text and then add a "Support us" navbar item in a contrasting color to the navbar all the way on the right. Thus button should only be shown when there isn't a user logged in. Maybe we can show the login name in that spot when a user is logged in?

**Comment by gentlecat** [comment]
Yeah, it might be better to have these parts of interface duplicated in the navbar. I didn't include that before because there was no space.
