### ISSUE TITLE
Hourly access threshold exceeded

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#99]
I received this message when I tried to have a replicated server catch up, meaning that it would need to copy a pile of replication packets in one hour. :(

We should tweak this check to only trigger if packets are being downloaded from a number of different IPs. For instance, if we have currently have more than 10 downloads for a token trigger this warning, we should change it to trigger it if more than 10 different IP addresses download it in an hour.

**Comment by gentlecat** [comment]
We'll need to store IP addresses in access logs then. https://github.com/metabrainz/metabrainz.org/blob/master/metabrainz/model/access_log.py

**Comment by mayhem** [comment]
But we only need them for a window of an hour, right? I don't mind storing them for a little while and then discarding them...

**Comment by gentlecat** [comment]
Right, we shouldn't need them after that one hour window.
